<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    protected $dontReport = [
        NoSufficientMoneyException::class
    ];
    protected $internalDontReport = [
        NoSufficientMoneyException::class
    ];
    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
    public function render($request, Throwable $e): \Illuminate\Http\Response|JsonResponse|RedirectResponse|Response
    {
        if ($e instanceof NoSufficientMoneyException) {
            return response()->json([
                'message' => $e->getMessage()
            ], $e->getCustomCode());
        }
        return parent::render($request, $e);
    }

    public function report(Throwable $e)
    {
        if ($e instanceof NoSufficientMoneyException) {
            return null;
        }
        return parent::report($e); // TODO: Change the autogenerated stub
    }

}
